name: Code quality
on: pull_request

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install -r tests/requirements.txt
      - name: Lint
        uses: TheFoundryVisionmongers/fn-pylint-action@v1.1
        with:
          pylint-rcfile: "./pyproject.toml"
          pylint-paths: >
            plugin
            tests

  black:
    runs-on: ubuntu-latest
    name: Python formatting
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install black

      - name: Check Python formatting
        run: black --check .
